version: '3.5'

services:
    db:
        image: mysql:8.0
        command: "mysqld --default-authentication-plugin=mysql_native_password"
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: Root_password!!._mysql!####
            MYSQL_DATABASE: eternaldb
            MYSQL_USER: eternalriw
            MYSQL_PASSWORD: Root_password!!._mysql!####

    php:
        build:
            dockerfile: docker/php/Dockerfile
            context: .
            target: production
    nginx:
        build:
            dockerfile: docker/nginx/Dockerfile
            context: .
        ports:
            - 8080:8080

